theme: jekyll-theme-minimal
title: "Kittiphon Phalakarn"
logo: "https://github.com/kittyphon/kittiphon.github.io/blob/master/pic.jpg?raw=true"
description: "kittiphon [dot] phalakarn [at] gmail [dot] com"
